/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PSMoveGestureRunner.java
 *
 * Created on Aug 29, 2011, 2:37:12 PM
 */

package psm;

import psm.PsMoveGestureSetupGUI.AnalysisMode;
import psm.PsMoveGestureSetupGUI.ControlMode;
import java.awt.AWTException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author fiebrink
 */
public class PSMoveGestureRunner extends javax.swing.JFrame {

    /** Creates new form PSMoveGestureRunner */
    public PSMoveGestureRunner() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionGroup = new javax.swing.ButtonGroup();
        recognizerGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboTask = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        labelSimulator = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboNumGestures = new javax.swing.JComboBox();
        comboActivity = new javax.swing.JComboBox();
        comboSimulator = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Finger movement type:");

        comboTask.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Target acquisition", "Shape drawing" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Activity:");

        labelSimulator.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSimulator.setText("Keyboard simulator behavior:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Number of movement types:");

        comboNumGestures.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboActivity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keyboard game", "Music" }));
        comboActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActivityActionPerformed(evt);
            }
        });

        comboSimulator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Key held down for gesture duration", "One keypress per unique gesture" }));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .add(labelSimulator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(comboActivity, 0, 283, Short.MAX_VALUE)
                            .add(comboNumGestures, 0, 283, Short.MAX_VALUE)
                            .add(comboTask, 0, 283, Short.MAX_VALUE)
                            .add(comboSimulator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(comboTask, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(comboNumGestures, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboActivity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelSimulator)
                    .add(comboSimulator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActivityActionPerformed
        if (comboActivity.getSelectedIndex() == 0) {
            setSimulatorEnabled(true);
        } else {
            setSimulatorEnabled(false);
        }
    }//GEN-LAST:event_comboActivityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numGestures = comboNumGestures.getSelectedIndex() + 1;
        String[] gestureNames = new String[numGestures];
        for (int i = 0; i < gestureNames.length; i++) {
            gestureNames[i] = "Gesture" + (i+1);
        }
        boolean doDtw = comboTask.getSelectedIndex() == 1;
        boolean doMusic = comboActivity.getSelectedIndex() == 1;
        boolean triggerContinuous = comboSimulator.getSelectedIndex() == 0;
        try {
            PsMoveGestureSetupGUI gui = new PsMoveGestureSetupGUI(gestureNames, triggerContinuous);
            this.dispose();
            /*        } catch (Exception ex) {
           
            } */
            //     public PsMoveGestureSetupGUI(String[] gestureNames, ControlMode controlMode, AnalysisMode analysisMode, final boolean constantTrigger) throws SocketException, UnknownHostException, AWTException, Exception {
        } catch (Exception ex) {
            System.out.println("Error encountered in running GUI: ");
            ex.printStackTrace();
            System.exit(0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void setSimulatorEnabled(boolean enabled) {
        labelSimulator.setEnabled(enabled);
        comboSimulator.setEnabled(enabled);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception ex) {
                }
                new PSMoveGestureRunner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup actionGroup;
    private javax.swing.JComboBox comboActivity;
    private javax.swing.JComboBox comboNumGestures;
    private javax.swing.JComboBox comboSimulator;
    private javax.swing.JComboBox comboTask;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSimulator;
    private javax.swing.ButtonGroup recognizerGroup;
    // End of variables declaration//GEN-END:variables

}
