/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplestDTWGUI.java
 *
 * Created on Aug 11, 2011, 1:58:45 PM
 */
package psm;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fiebrink
 */
public class SimplestTargetGUI extends javax.swing.JFrame {

    SimplestTarget1 targeter;
    double myThreshold = 25.0;

    /** Creates new form SimplestDTWGUI */
    public SimplestTargetGUI() {
        initComponents();
        try {
            targeter = new SimplestTarget1();
            targeter.addPropertyChangeListener(new PropertyChangeListener() {

                public void propertyChange(PropertyChangeEvent pce) {
                    if (pce.getPropertyName().equals(SimplestDTW.PROP_MAXDISTANCE)) {
                        double newDist = targeter.getMaxDistance();
                        if (newDist > myThreshold) {
                            sliderThreshold.setMaximum((int) (100 * newDist) + 1);
                        } else {
                            sliderThreshold.setMaximum((int) (100 * myThreshold) + 1);
                        }
                        System.out.println("Slider max set to " + sliderThreshold.getMaximum());

                    } else if (pce.getPropertyName().equals(SimplestDTW.PROP_CONTINUOUSMATCH)) {
                        int match = targeter.getContinuousMatch();
                        if (match == -1) {
                            labelContinuousOutput.setText("NONE");

                        } else {
                            labelContinuousOutput.setText("" + (match));
                        }
                    }

                }
            });



        } catch (Exception ex) {
            System.out.println("Exception encountered: " + ex);
            Logger.getLogger(SimplestTargetGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAdd1 = new javax.swing.JButton();
        buttonDelete1 = new javax.swing.JButton();
        buttonDelete2 = new javax.swing.JButton();
        labelNum1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNum2 = new javax.swing.JLabel();
        buttonAdd2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        toggleRunContinuously = new javax.swing.JToggleButton();
        labelContinuousOutput = new javax.swing.JLabel();
        labelDistanceTo1 = new javax.swing.JLabel();
        labelDistanceTo2 = new javax.swing.JLabel();
        labelMatchThreshold = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sliderThreshold = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        labelT1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Example Targets"));

        buttonAdd1.setText("Add Target 1");
        buttonAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAdd1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAdd1MouseReleased(evt);
            }
        });
        buttonAdd1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonAdd1StateChanged(evt);
            }
        });
        buttonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdd1ActionPerformed(evt);
            }
        });

        buttonDelete1.setText("Delete Target 1");
        buttonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete1ActionPerformed(evt);
            }
        });

        buttonDelete2.setText("Delete Target 2");
        buttonDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete2ActionPerformed(evt);
            }
        });

        labelNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum1.setText("0");

        jLabel2.setText("# recorded");

        labelNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum2.setText("0");

        buttonAdd2.setText("Add Target 1");
        buttonAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAdd2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAdd2MouseReleased(evt);
            }
        });
        buttonAdd2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonAdd2StateChanged(evt);
            }
        });
        buttonAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdd2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(buttonAdd1)
                            .add(buttonAdd2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonDelete1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelNum1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonDelete2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(labelNum2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(313, 313, 313)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(buttonDelete2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelNum2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(buttonAdd2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(buttonDelete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(buttonAdd1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(labelNum1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Run Gesture Recognizer"));

        toggleRunContinuously.setText("Run Continuously");
        toggleRunContinuously.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRunContinuouslyActionPerformed(evt);
            }
        });

        labelContinuousOutput.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelContinuousOutput.setText("none");

        labelDistanceTo1.setText("Distance to 1: 0.3523549");

        labelDistanceTo2.setText("Distance to 2: 0.3523549");

        labelMatchThreshold.setText("Match threshold: 10");

        sliderThreshold.setMaximum(5000);
        sliderThreshold.setValue(1000);
        sliderThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderThresholdStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(sliderThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(sliderThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(labelMatchThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(toggleRunContinuously, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelContinuousOutput)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelDistanceTo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelDistanceTo2, 0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelMatchThreshold)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(toggleRunContinuously, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(labelDistanceTo1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelDistanceTo2))
                            .add(labelContinuousOutput)))))
        );

        jButton1.setText("print debug info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Joint1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Joint3");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Joint2");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        labelT1.setText(".001");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox2)
                        .add(18, 18, 18)
                        .add(labelT1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jCheckBox1)
                    .add(jCheckBox3)
                    .add(jCheckBox2)
                    .add(labelT1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdd1ActionPerformed
    }//GEN-LAST:event_buttonAdd1ActionPerformed

    private void buttonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete1ActionPerformed
        targeter.deleteExamples(0);
        labelNum1.setText("0");
    }//GEN-LAST:event_buttonDelete1ActionPerformed

    private void buttonDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete2ActionPerformed
        targeter.deleteExamples(1);
        labelNum2.setText("0");
    }//GEN-LAST:event_buttonDelete2ActionPerformed

    private void buttonAdd1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd1MousePressed
        targeter.setCurrentTrainingGesture(0);
        targeter.startRecording();
    }//GEN-LAST:event_buttonAdd1MousePressed

    private void buttonAdd1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonAdd1StateChanged
    }//GEN-LAST:event_buttonAdd1StateChanged

    private void buttonAdd1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd1MouseReleased
        targeter.stopRecording();
        int n = targeter.getNumExamples(0);
        labelNum1.setText(Integer.toString(n));
    }//GEN-LAST:event_buttonAdd1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        targeter.printState();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toggleRunContinuouslyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRunContinuouslyActionPerformed
        if (toggleRunContinuously.isSelected()) {
            targeter.startRunning();
        } else {
            targeter.stopRunning();
        }

        System.out.println(toggleRunContinuously.isSelected());
    }//GEN-LAST:event_toggleRunContinuouslyActionPerformed

    private void sliderThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderThresholdStateChanged
        double t = sliderThreshold.getValue() * .01;
        targeter.setMatchThreshold(t);

        labelMatchThreshold.setText("Match threshold: " + t);
        myThreshold = sliderThreshold.getValue() * .01;
    }//GEN-LAST:event_sliderThresholdStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        updateFeatures();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        updateFeatures();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        updateFeatures();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void buttonAdd2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd2MousePressed
        targeter.setCurrentTrainingGesture(1);
        targeter.startRecording();
    }//GEN-LAST:event_buttonAdd2MousePressed

    private void buttonAdd2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd2MouseReleased
        targeter.stopRecording();
        int n = targeter.getNumExamples(1);
        labelNum2.setText(Integer.toString(n));
    }//GEN-LAST:event_buttonAdd2MouseReleased

    private void buttonAdd2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonAdd2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdd2StateChanged

    private void buttonAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdd2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double t = Double.parseDouble(labelT1.getText());
        targeter.setMatchThreshold(t);

        labelMatchThreshold.setText("Match threshold: " + t);
}//GEN-LAST:event_jButton3ActionPerformed

    private void updateFeatures() {
        boolean enabled[] = new boolean[3];
        enabled[0] = jCheckBox1.isSelected();
        enabled[1] = jCheckBox2.isSelected();
        enabled[2] = jCheckBox3.isSelected();
        targeter.setEnabledFeatures(enabled);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SimplestTargetGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd1;
    private javax.swing.JButton buttonAdd2;
    private javax.swing.JButton buttonDelete1;
    private javax.swing.JButton buttonDelete2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelContinuousOutput;
    private javax.swing.JLabel labelDistanceTo1;
    private javax.swing.JLabel labelDistanceTo2;
    private javax.swing.JLabel labelMatchThreshold;
    private javax.swing.JLabel labelNum1;
    private javax.swing.JLabel labelNum2;
    private javax.swing.JTextField labelT1;
    private javax.swing.JSlider sliderThreshold;
    private javax.swing.JToggleButton toggleRunContinuously;
    // End of variables declaration//GEN-END:variables
}
