/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplestDTWGUI.java
 *
 * Created on Aug 11, 2011, 1:58:45 PM
 */

package psm;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author fiebrink
 */
public class SimplestDTWGUI extends javax.swing.JFrame {

    SimplestDTW dtwer;
    double myThreshold = 25.0;

    /** Creates new form SimplestDTWGUI */
    public SimplestDTWGUI() {
        initComponents();
        try {
            dtwer = new SimplestDTW();
            dtwer.addPropertyChangeListener(new PropertyChangeListener() {

                public void propertyChange(PropertyChangeEvent pce) {
                    if (pce.getPropertyName().equals(SimplestDTW.PROP_MAXDISTANCE)) {
                        double newDist = dtwer.getMaxDistance();
                        if (newDist > myThreshold) {
                            sliderThreshold.setMaximum((int)(100*newDist) + 1);
                        } else {
                            sliderThreshold.setMaximum((int)(100*myThreshold) + 1);
                        }
                        System.out.println("Slider max set to " + sliderThreshold.getMaximum());

                    } else if (pce.getPropertyName().equals(SimplestDTW.PROP_CONTINUOUSMATCH)) {
                        int match = dtwer.getContinuousMatch();
                        if (match == -1) {
                            labelContinuousOutput.setText("NONE");
                            
                        } else {
                            labelContinuousOutput.setText("" + (match));
                        }
                    }

                }
            });



        } catch (Exception ex) {
            System.out.println("Exception encountered: " + ex);
            Logger.getLogger(SimplestDTWGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAdd1 = new javax.swing.JButton();
        buttonAdd2 = new javax.swing.JButton();
        buttonDelete1 = new javax.swing.JButton();
        buttonDelete2 = new javax.swing.JButton();
        labelNum1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNum2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        toggleRunContinuously = new javax.swing.JToggleButton();
        labelContinuousOutput = new javax.swing.JLabel();
        buttonClassifySingle = new javax.swing.JButton();
        labelClassifiedAs = new javax.swing.JLabel();
        labelDistanceTo1 = new javax.swing.JLabel();
        labelDistanceTo2 = new javax.swing.JLabel();
        labelMatchThreshold = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sliderThreshold = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        labelT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Example Gestures"));

        buttonAdd1.setText("Add Gesture 1");
        buttonAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAdd1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAdd1MouseReleased(evt);
            }
        });
        buttonAdd1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonAdd1StateChanged(evt);
            }
        });
        buttonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdd1ActionPerformed(evt);
            }
        });

        buttonAdd2.setText("Add Gesture 2");
        buttonAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAdd2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAdd2MouseReleased(evt);
            }
        });
        buttonAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdd2ActionPerformed(evt);
            }
        });

        buttonDelete1.setText("Delete Gesture 1");
        buttonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete1ActionPerformed(evt);
            }
        });

        buttonDelete2.setText("Delete Gesture 2");
        buttonDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete2ActionPerformed(evt);
            }
        });

        labelNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum1.setText("0");

        jLabel2.setText("# recorded");

        labelNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum2.setText("0");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonAdd2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonAdd1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonDelete1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelNum1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonDelete2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(labelNum2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(313, 313, 313)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(buttonAdd2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(buttonDelete2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelNum2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(buttonDelete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(buttonAdd1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(labelNum1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Run Gesture Recognizer"));

        toggleRunContinuously.setText("Run Continuously");
        toggleRunContinuously.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRunContinuouslyActionPerformed(evt);
            }
        });

        labelContinuousOutput.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelContinuousOutput.setText("none");

        buttonClassifySingle.setText("Classify Single");
        buttonClassifySingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClassifySingleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonClassifySingleMouseReleased(evt);
            }
        });
        buttonClassifySingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassifySingleActionPerformed(evt);
            }
        });

        labelClassifiedAs.setText("Classified as: 1");

        labelDistanceTo1.setText("Distance to 1: 0.3523549");

        labelDistanceTo2.setText("Distance to 2: 0.3523549");

        labelMatchThreshold.setText("Match threshold: 10");

        sliderThreshold.setMaximum(5000);
        sliderThreshold.setValue(1000);
        sliderThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderThresholdStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(sliderThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(sliderThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(buttonClassifySingle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(18, 18, 18))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(toggleRunContinuously, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(labelContinuousOutput)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(labelClassifiedAs)
                            .add(labelDistanceTo2, 0, 0, Short.MAX_VALUE)
                            .add(labelDistanceTo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 284, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .add(jPanel2Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelMatchThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelMatchThreshold)
                .add(55, 55, 55)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(buttonClassifySingle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(labelClassifiedAs)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelDistanceTo1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelDistanceTo2)))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(toggleRunContinuously, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelContinuousOutput))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("print debug info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelT.setText(".001");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 195, Short.MAX_VALUE)
                        .add(labelT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(labelT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2))
                .add(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdd1ActionPerformed
    }//GEN-LAST:event_buttonAdd1ActionPerformed

    private void buttonAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdd2ActionPerformed

    private void buttonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete1ActionPerformed
        dtwer.deleteExamples(0);
        labelNum1.setText("0");
    }//GEN-LAST:event_buttonDelete1ActionPerformed

    private void buttonDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete2ActionPerformed
        dtwer.deleteExamples(1);
        labelNum2.setText("0");
    }//GEN-LAST:event_buttonDelete2ActionPerformed

    private void buttonClassifySingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassifySingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClassifySingleActionPerformed

    private void buttonAdd1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd1MousePressed
        dtwer.setCurrentTrainingGesture(0);
        dtwer.startRecording();
    }//GEN-LAST:event_buttonAdd1MousePressed

    private void buttonAdd1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonAdd1StateChanged
        
    }//GEN-LAST:event_buttonAdd1StateChanged

    private void buttonAdd1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd1MouseReleased
        dtwer.stopRecording();
        int n = dtwer.getNumExamples(0);
        labelNum1.setText(Integer.toString(n));
    }//GEN-LAST:event_buttonAdd1MouseReleased

    private void buttonClassifySingleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClassifySingleMousePressed
        dtwer.startRunningSingle();
    }//GEN-LAST:event_buttonClassifySingleMousePressed

    private void buttonClassifySingleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClassifySingleMouseReleased
        dtwer.stopRunning();
        int whichClass = dtwer.classifyLast();
        double dist1 = dtwer.getLastDistance(0);
        double dist2 = dtwer.getLastDistance(1);
        labelClassifiedAs.setText("Classified as: " + whichClass);
        labelDistanceTo1.setText("Distance to 1: " + dist1);
        labelDistanceTo2.setText("Distance to 2: " + dist2);
    }//GEN-LAST:event_buttonClassifySingleMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dtwer.printState();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonAdd2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd2MousePressed
        dtwer.setCurrentTrainingGesture(1);
        dtwer.startRecording();    }//GEN-LAST:event_buttonAdd2MousePressed

    private void buttonAdd2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdd2MouseReleased
        dtwer.stopRecording();
        int n = dtwer.getNumExamples(1);
        labelNum2.setText(Integer.toString(n));    }//GEN-LAST:event_buttonAdd2MouseReleased

    private void toggleRunContinuouslyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRunContinuouslyActionPerformed
        if (toggleRunContinuously.isSelected()) {
            dtwer.startRunningContinuous();
        } else {
            dtwer.stopRunning();
        }

        System.out.println(toggleRunContinuously.isSelected());
    }//GEN-LAST:event_toggleRunContinuouslyActionPerformed

    private void sliderThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderThresholdStateChanged
        double t = sliderThreshold.getValue() * .01;
        dtwer.setMatchThreshold(t);

        labelMatchThreshold.setText("Match threshold: " + t);
    }//GEN-LAST:event_sliderThresholdStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double t = Double.parseDouble(labelT.getText());
        dtwer.setMatchThreshold(t);

        labelMatchThreshold.setText("Match threshold: " + t);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimplestDTWGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd1;
    private javax.swing.JButton buttonAdd2;
    private javax.swing.JButton buttonClassifySingle;
    private javax.swing.JButton buttonDelete1;
    private javax.swing.JButton buttonDelete2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelClassifiedAs;
    private javax.swing.JLabel labelContinuousOutput;
    private javax.swing.JLabel labelDistanceTo1;
    private javax.swing.JLabel labelDistanceTo2;
    private javax.swing.JLabel labelMatchThreshold;
    private javax.swing.JLabel labelNum1;
    private javax.swing.JLabel labelNum2;
    private javax.swing.JTextField labelT;
    private javax.swing.JSlider sliderThreshold;
    private javax.swing.JToggleButton toggleRunContinuously;
    // End of variables declaration//GEN-END:variables

}
